# Imports

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

# Dataset path

In [2]:
TRAIN_PATH = "../data/raw/fraudTrain.csv"
TEST_PATH = "../data/raw/fraudTest.csv"

# Read a sample

In [3]:
df_sample = pd.read_csv(TRAIN_PATH, nrows=10_000)

df_sample.shape

(10000, 23)

# Inspect the schema

In [4]:
df_sample.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,NC,28654,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,ID,83252,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,VA,24433,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [5]:
df_sample.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             10000 non-null  int64
 1   trans_date_trans_time  10000 non-null  str
 2   cc_num                 10000 non-null  int64
 3   merchant               10000 non-null  str
 4   category               10000 non-null  str
 5   amt                    10000 non-null  float64
 6   first                  10000 non-null  str
 7   last                   10000 non-null  str
 8   gender                 10000 non-null  str
 9   street                 10000 non-null  str
 10  city                   10000 non-null  str
 11  state                  10000 non-null  str
 12  zip                    10000 non-null  int64
 13  lat                    10000 non-null  float64
 14  long                   10000 non-null  float64
 15  city_pop               10000 non-null  int64
 16  job                    10000 non-null  str
 17  dob                    10000 non-null  str
 18  trans_num              10000 non-null  str
 19  unix_time              10000 non-null  int64
 20  merch_lat              10000 non-null  float64
 21  merch_long             10000 non-null  float64
 22  is_fraud               10000 non-null  int64
dtypes: float64(5), int64(6), str(12)
memory usage: 1.8 MB

In [6]:
df_sample.columns.tolist()

['Unnamed: 0',
 'trans_date_trans_time',
 'cc_num',
 'merchant',
 'category',
 'amt',
 'first',
 'last',
 'gender',
 'street',
 'city',
 'state',
 'zip',
 'lat',
 'long',
 'city_pop',
 'job',
 'dob',
 'trans_num',
 'unix_time',
 'merch_lat',
 'merch_long',
 'is_fraud']

In [7]:
df_sample.dtypes

Unnamed: 0                 int64
trans_date_trans_time        str
cc_num                     int64
merchant                     str
category                     str
amt                      float64
first                        str
last                         str
gender                       str
street                       str
city                         str
state                        str
zip                        int64
lat                      float64
long                     float64
city_pop                   int64
job                          str
dob                          str
trans_num                    str
unix_time                  int64
merch_lat                float64
merch_long               float64
is_fraud                   int64
dtype: object

# Inspect the target

In [8]:
df_sample["is_fraud"].value_counts()

is_fraud
0    9953
1      47
Name: count, dtype: int64

In [9]:
df_sample["is_fraud"].value_counts(normalize=True) * 100

is_fraud
0    99.53
1     0.47
Name: proportion, dtype: float64

# Missing values

In [10]:
missing = (
    df_sample.isna()
    .sum()
    .sort_values(ascending=False)
)

missing[missing > 0]

Series([], dtype: int64)

# Basic statistics

In [12]:
df_sample.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Unnamed: 0,10000.0,NaN,NaN,NaN,4999.5,2886.89568,0.0,2499.75,4999.5,7499.25,9999.0
trans_date_trans_time,10000,9895,2019-01-01 16:52:19,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cc_num,10000.0,NaN,NaN,NaN,424016607817188800.0,1318553111362664192.0,60416207185.0,180036456789979.0,3520550088202337.0,4657269323674365.0,4992346398065154048.0
merchant,10000,693,fraud_Kilback LLC,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
category,10000,14,gas_transport,1071,NaN,NaN,NaN,NaN,NaN,NaN,NaN
amt,10000.0,NaN,NaN,NaN,68.413486,111.527924,1.01,9.69,48.675,83.0925,3178.51
first,10000,335,Christopher,205,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last,10000,462,Smith,211,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,10000,2,F,5485,NaN,NaN,NaN,NaN,NaN,NaN,NaN
street,10000,903,43039 Riley Greens Suite 393,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,10000,832,San Antonio,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state,10000,50,TX,706,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zip,10000.0,NaN,NaN,NaN,49325.4353,27188.598694,1257.0,25832.0,48438.0,72341.0,99783.0
lat,10000.0,NaN,NaN,NaN,38.593693,5.180796,20.0271,34.7789,39.3832,41.8467,65.6899
long,10000.0,NaN,NaN,NaN,-90.617579,14.458799,-165.6723,-97.1714,-87.7246,-80.1284,-67.9503
city_pop,10000.0,NaN,NaN,NaN,89853.3804,300119.774765,23.0,741.0,2398.0,19090.0,2906700.0
job,10000,475,"Designer, ceramics/pottery",78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dob,10000,889,1977-03-23,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN
trans_num,10000,10000,0b242abb623afc578575680df30655b9,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unix_time,10000.0,NaN,NaN,NaN,1325645003.3846,167900.273541,1325376018.0,1325472050.25,1325654178.5,1325800837.0,1325908434.0
merch_lat,10000.0,NaN,NaN,NaN,38.593578,5.209553,19.165823,34.84739,39.370857,41.899369,66.645176
merch_long,10000.0,NaN,NaN,NaN,-90.608638,14.476713,-166.550779,-97.224395,-87.66408,-80.181638,-66.967742
is_fraud,10000.0,NaN,NaN,NaN,0.0047,0.068399,0.0,0.0,0.0,0.0,1.0

In [13]:
df_sample[[
    "trans_date_trans_time",
    "category",
    "amt",
    "gender",
    "city",
    "state",
    "lat",
    "long",
    "merch_lat",
    "merch_long",
    "is_fraud"
]].head(20)

,trans_date_trans_time,category,amt,gender,city,state,lat,long,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,misc_net,4.97,F,Moravian Falls,NC,36.0788,-81.1781,36.011293,-82.048315,0
1,2019-01-01 00:00:44,grocery_pos,107.23,F,Orient,WA,48.8878,-118.2105,49.159047,-118.186462,0
2,2019-01-01 00:00:51,entertainment,220.11,M,Malad City,ID,42.1808,-112.2620,43.150704,-112.154481,0
3,2019-01-01 00:01:16,gas_transport,45.00,M,Boulder,MT,46.2306,-112.1138,47.034331,-112.561071,0
4,2019-01-01 00:03:06,misc_pos,41.96,M,Doe Hill,VA,38.4207,-79.4629,38.674999,-78.632459,0
5,2019-01-01 00:04:08,gas_transport,94.63,F,Dublin,PA,40.3750,-75.2045,40.653382,-76.152667,0
6,2019-01-01 00:04:42,grocery_net,44.54,F,Holcomb,KS,37.9931,-100.9893,37.162705,-100.153370,0
7,2019-01-01 00:05:08,gas_transport,71.65,M,Edinburg,VA,38.8432,-78.6003,38.948089,-78.540296,0
8,2019-01-01 00:05:18,misc_pos,4.27,F,Manor,PA,40.3359,-79.6607,40.351813,-79.958146,0
9,2019-01-01 00:06:01,grocery_pos,198.39,F,Clarksville,TN,36.5220,-87.3490,37.179198,-87.485381,0
10,2019-01-01 00:06:23,grocery_pos,24.74,M,Clarinda,IA,40.7491,-95.0380,40.275891,-96.011548,0
11,2019-01-01 00:06:53,shopping_net,7.77,F,Shenandoah Junction,WV,39.3716,-77.8229,40.103866,-78.624459,0
12,2019-01-01 00:06:56,grocery_pos,71.22,M,Saint Petersburg,FL,27.7898,-82.7243,27.630593,-82.308891,0
13,2019-01-01 00:07:27,grocery_pos,96.29,M,Grenada,CA,41.6125,-122.5258,41.657520,-122.230347,0
14,2019-01-01 00:09:03,shopping_pos,7.77,M,High Rolls Mountain Park,NM,32.9396,-105.8189,32.863258,-106.520205,0
15,2019-01-01 00:09:20,shopping_net,3.26,M,Harrington Park,NJ,40.9918,-73.9800,41.831174,-74.335559,0
16,2019-01-01 00:10:49,misc_net,327.00,F,Lahoma,OK,36.3850,-98.0727,36.384092,-99.048472,0
17,2019-01-01 00:10:58,shopping_pos,341.67,M,Carlisle,IN,38.9763,-87.3667,38.674491,-88.305767,0
18,2019-01-01 00:11:14,food_dining,63.07,M,Harborcreek,PA,42.1767,-79.9416,41.430274,-79.492553,0
19,2019-01-01 00:12:34,grocery_pos,44.71,M,Elizabeth,NJ,40.6747,-74.2239,40.079588,-74.848087,0

In [14]:
from pathlib import Path

TRAIN_PATH = Path("../data/raw/fraudTrain.csv")
TEST_PATH = Path("../data/raw/fraudTest.csv")

print(f"Train size: {TRAIN_PATH.stat().st_size / (1024**2):.2f} MB")
print(f"Test size:  {TEST_PATH.stat().st_size / (1024**2):.2f} MB")

Train size: 334.97 MB
Test size:  143.39 MB

In [15]:
def fraud_distribution(path):
    counts = {0: 0, 1: 0}
    
    for chunk in pd.read_csv(path, usecols=["is_fraud"], chunksize=100_000):
        values = chunk["is_fraud"].value_counts()
        
        counts[0] += values.get(0, 0)
        counts[1] += values.get(1, 0)
    
    total = counts[0] + counts[1]
    
    return pd.Series({
        "legitimate": counts[0],
        "fraud": counts[1],
        "total": total,
        "fraud_percentage": counts[1] / total * 100
    })

In [16]:
train_fraud = fraud_distribution(TRAIN_PATH)
test_fraud = fraud_distribution(TEST_PATH)

print("TRAIN")
display(train_fraud)

print("\nTEST")
display(test_fraud)

TRAIN

legitimate          1.289169e+06
fraud               7.506000e+03
total               1.296675e+06
fraud_percentage    5.788652e-01
dtype: float64

TEST

legitimate          553574.000000
fraud                 2145.000000
total               555719.000000
fraud_percentage         0.385986
dtype: float64

In [17]:
# Load only the date column
train_dates = pd.read_csv(
    TRAIN_PATH,
    usecols=["trans_date_trans_time"]
)

test_dates = pd.read_csv(
    TEST_PATH,
    usecols=["trans_date_trans_time"]
)

train_dates["trans_date_trans_time"] = pd.to_datetime(
    train_dates["trans_date_trans_time"]
)

test_dates["trans_date_trans_time"] = pd.to_datetime(
    test_dates["trans_date_trans_time"]
)

print("TRAIN")
print("Start:", train_dates["trans_date_trans_time"].min())
print("End:  ", train_dates["trans_date_trans_time"].max())

print("\nTEST")
print("Start:", test_dates["trans_date_trans_time"].min())
print("End:  ", test_dates["trans_date_trans_time"].max())

TRAIN
Start: 2019-01-01 00:00:18
End:   2020-06-21 12:13:37

TEST
Start: 2020-06-21 12:14:25
End:   2020-12-31 23:59:34

In [18]:
print("Unique cards in train:", 
      pd.read_csv(TRAIN_PATH, usecols=["cc_num"])["cc_num"].nunique())

print("Unique cards in test:", 
      pd.read_csv(TEST_PATH, usecols=["cc_num"])["cc_num"].nunique())

Unique cards in train: 983
Unique cards in test: 924

In [19]:
train_cards = set(
    pd.read_csv(
        TRAIN_PATH,
        usecols=["cc_num"]
    )["cc_num"]
)

test_cards = set(
    pd.read_csv(
        TEST_PATH,
        usecols=["cc_num"]
    )["cc_num"]
)

overlap = train_cards & test_cards

print("Train cards:", len(train_cards))
print("Test cards:", len(test_cards))
print("Cards appearing in both:", len(overlap))
print(
    "Test cards seen during training:",
    len(overlap) / len(test_cards) * 100,
    "%"
)

Train cards: 983
Test cards: 924
Cards appearing in both: 908
Test cards seen during training: 98.26839826839827 %